---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR'] %>
  region: <%= ENV['AWS_REGION'] %>
  security_group_ids: 
    - <%= ENV['AWS_SECURITY_GROUP_ID'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  vpc_id: <%= ENV['AWS_VPC_ID'] %>
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for <YOURNAME>, <%= ENV['TRAINER_NAME'] %>"
    user: Administrator
    X-Contact: <%= ENV['TRAINER_NAME'] %>
    X-Application: "Training"
    X-Dept: "sales"
    X-Customer: <%= ENV['TRAINER_NAME'] %>
    X-Project: "Student_Lab"
    X-TTL: 4

provisioner:
  name: chef_zero
  product_name: chef
  chef_license: accept
  product_version: 15.12.22
  
verifier:
  name: inspec
  format: documentation

platforms:
  - name: ubuntu-16.04
    driver:
      image_id: ami-042b1570ee0c84f5a
    transport:
      username: ubuntu
      ssh_key: C:\Users\Chef\.ssh\id_rsa
    driver_config:
      user_data: C:/Users/chef/user_data

suites:
  - name: default
    run_list:
      - recipe[ap_ubuntu_bootstrap::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      environment:
       automate_url: <%= ENV['AUTOMATE_HOSTNAME'] %>
       chef_org: <%= ENV['CHEF_ORG'] %>
  - name: default_2
    run_list:
      - recipe[ap_ubuntu_bootstrap::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      environment:
       automate_url: <%= ENV['AUTOMATE_HOSTNAME'] %>
       chef_org: <%= ENV['CHEF_ORG'] %>
  - name: default_3
    run_list:
      - recipe[ap_ubuntu_bootstrap::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      environment:
       automate_url: <%= ENV['AUTOMATE_HOSTNAME'] %>
       chef_org: <%= ENV['CHEF_ORG'] %>
